### ISSUE TITLE
Top silkscreen on host connector

### ISSUE THREAD

**Issue by k0d** [nitz/OpenClip#1]
It feels like it's too much silkscreen, takes your eye away from the rest of the board.

Here is my suggestion.

<img width="332" alt="Screenshot 2020-08-29 at 18 06 26" src="https://user-images.githubusercontent.com/547698/91641077-62776180-ea22-11ea-9156-895309d608f1.png">

<img width="262" alt="Screenshot 2020-08-29 at 18 03 17" src="https://user-images.githubusercontent.com/547698/91641040-2a701e80-ea22-11ea-82bf-3fc23a9369e2.png">

**Comment by nitz** [comment]
I'll let @tannewt chime in if he'd like, but in my opinion I feel like that's a bit of the point: to draw your eyes to it and be immediately recognizable. ETA: I also haven't seen it on a more standard sized board as a whole yet, so perhaps I'm under estimating that the 10p version is only 1cm long.

I also think your render in particular makes it a bit more difficult to see there, since your pads are colored the same as the silk. When the pads are actually gold or silver, I think they stand out a bit more: 
![image](https://user-images.githubusercontent.com/602691/91642330-8920a280-e9f8-11ea-8d71-3bbf60ae5ee5.png)

**Comment by k0d** [comment]
<img width="874" alt="Screenshot 2020-08-29 at 18 18 20" src="https://user-images.githubusercontent.com/547698/91641353-0a415f00-ea24-11ea-8742-9b82bb726122.png">

This is what I think would look better. It looks great on the board I'm making...

**Comment by k0d** [comment]
Maybe the targets silkscreen isn't great on my above render...

I also wonder...maybe we'd like to include some text or a little 'logo'? then it's even more recognisable....

**Comment by nitz** [comment]
Yeah I did a very quick mspaint mockup where I just plopped a random little gear/arrow logo on one of Scott's images: 
![image](https://user-images.githubusercontent.com/602691/91642661-2d0b4d80-e9fb-11ea-8f84-b53a990636bc.png)

I'm definitely no artist, but I love the idea of a tiny logo that is an immediate "oh i know what this is" hint.

**Comment by k0d** [comment]
Leave that to me...I'll produce some mock-ups in a couple of hours. :)

**Comment by k0d** [comment]
Suggestion for the host connector.

<img width="969" alt="Screenshot 2020-08-29 at 21 06 43" src="https://user-images.githubusercontent.com/547698/91644393-db36e780-ea3b-11ea-8712-fd3790658d4b.png">

<img width="646" alt="Screenshot 2020-08-29 at 21 10 17" src="https://user-images.githubusercontent.com/547698/91644419-0cafb300-ea3c-11ea-82e6-1d2188f01a8e.png">

**Comment by nitz** [comment]
Ooh, that's fun! I definitely like the spider too. In my quick hunt for "debugging" related iconography I kept coming across things like this that I found on nounproject: ![image](https://user-images.githubusercontent.com/602691/91644456-220be980-ea0a-11ea-82c7-0372ed520ac5.png))

Somehow the spider comes off a lot less "creepy" than the fewer-legged one. Plus I hear they're pretty good at eating bugs!

**Comment by k0d** [comment]
haha...yeah, also...the target connector could have a web around it or something...not started to design that yet.

@tannewt your opinion?

**Comment by k0d** [comment]
Host and target

Probably the arrows on the 'web' I'll change them...

![Screenshot 2020-08-29 at 21 22 29](https://user-images.githubusercontent.com/547698/91644609-f3a80180-ea3d-11ea-9e73-f43c25a6144a.jpg)

**Comment by k0d** [comment]
<img width="767" alt="Screenshot 2020-08-29 at 21 36 48" src="https://user-images.githubusercontent.com/547698/91644800-dc6a1380-ea3f-11ea-81a1-d3e45477ab53.png">

**Comment by tannewt** [comment]
These look like neat ideas. The spider is a great idea! We could use that as the general logo too.

My main goal with the heavy silkscreen was to make the top easily distinguishable from the bottom.

I don't think we'll know what works best until we start seeing it on real boards. All of these renders are much larger that it will be in real life.

**Comment by nitz** [comment]
That's a really good point. I swear I need to get a to-scale model of a quarter and keep it every board I do. Sounds like the first spins at oshpark are already at the fab so hopefully we'll get it a good look quickly!

**Comment by k0d** [comment]
<img width="451" alt="Screenshot 2020-08-29 at 21 59 41" src="https://user-images.githubusercontent.com/547698/91645140-f3f6cb80-ea42-11ea-800c-ebc8a15b453b.png">

This is a minimalist version of it.

I'm going to order a prototype board for a project tomorrow, I'll order a board with each of my examples to compare.

Yes, I was thinking we can use the spider as a logo also.

**Comment by tannewt** [comment]
@k0d do you not like the slanted pads? I like having a version that would work without silkscreen.

**Comment by k0d** [comment]
<img width="502" alt="Screenshot 2020-08-29 at 22 11 54" src="https://user-images.githubusercontent.com/547698/91645354-b004c600-ea44-11ea-8edc-c86fa255bae6.png">

Personally...no I don't like them...but I agree with you...

**Comment by k0d** [comment]
It's hard to get the spider+text to be nice with the slants...but I'm working on it...

**Comment by tannewt** [comment]
I'm ok omitting the text too and just having the spider.

**Comment by nitz** [comment]
I agree with that. The spider is something that would be recognizable, and something someone could google "spider connector" or something like that 😂

**Comment by k0d** [comment]
<img width="894" alt="Screenshot 2020-08-29 at 22 32 00" src="https://user-images.githubusercontent.com/547698/91645697-77b2b700-ea47-11ea-98b5-9bd041c9b343.png">

What do you think of the bottom left one? I will fix the slanted pads...

**Comment by k0d** [comment]
<img width="263" alt="Screenshot 2020-08-29 at 22 34 09" src="https://user-images.githubusercontent.com/547698/91645721-c3656080-ea47-11ea-995a-06482e0ca9bc.png">

Green + HASL. (This is what my next board will be...so I am keen to make it look nice on it)

**Comment by k0d** [comment]
<img width="536" alt="Screenshot 2020-08-29 at 22 47 12" src="https://user-images.githubusercontent.com/547698/91645876-974adf00-ea49-11ea-80d6-7840cdcea717.png">

**Comment by k0d** [comment]
<img width="752" alt="Screenshot 2020-08-29 at 23 16 30" src="https://user-images.githubusercontent.com/547698/91646294-f14da380-ea4d-11ea-8c31-4b55fad65d41.png">

I feel this is the 'final design' from my point of view...so now it's up to you to let me know what you think, should I change anything and if you want to use it.

**Comment by nitz** [comment]
I actually _really_ like it. The IC shape on the target side side is super cute. I don't know how it would work at that scale, but you gave me the idea of trying to put like, a "webbing" inside of it. Excusing my (very) poor mspaint rendition:

![image](https://user-images.githubusercontent.com/602691/91647417-96ee1c00-ea28-11ea-8f3d-0bbc9e2843ab.png)
(Or like you have with the chip, then use mask to 'paint' the web lines?)

Again, I know it's super tiny and I'm not sure how well it'd look at that scale, but I feel like it would hit the theme spot on.

You also gave me an idea for a swankied up wordmark with the way you did the in/out style like that:

![image](https://user-images.githubusercontent.com/602691/91647471-14b22780-ea29-11ea-871b-9ddca3884a6c.png)

**Comment by k0d** [comment]
I think its a no with the web....too small, am already pushing the limits as it is.

The Logo...nice start. Will think about that tomorrow...

**Comment by tannewt** [comment]
I really like the spider on one side and the ic on the other!

**Comment by k0d** [comment]
<img width="636" alt="Screenshot 2020-08-30 at 20 08 08" src="https://user-images.githubusercontent.com/547698/91666384-8909cb00-eafc-11ea-87ab-6494b866a4c7.png">

I've changed the silkscreen a little...and optimised the images...as it took like 1 minute to do the copper flood fill command as there was so many edges for it to work around...now it's normal speed.

If you like this...I'm going to order a prototype of a board I'm going to be selling...which I want to use this connector on. I understand it's still work in progress, but I'd like to get as close to a real connector as possible so any prototype users will not get confused if it's changed a lot.

**Comment by tannewt** [comment]
I was thinking the slant would peak at the slot. For the target side I wanted a slant as well as to make the gnd pin stick out further to “fit” into the host “plug”.

**Comment by k0d** [comment]
Ok...I need a bit more info about that, I don't really understand what you want to achieve with it...

**Comment by tannewt** [comment]
Sorry. I’m on my phone so I’m a bit limited. For the target, I was going to set back all pins except gnd by the same amount as the gnd pin on the host. That help? Otherwise I can try and implement it later.

**Comment by k0d** [comment]
Ok, I get that...was there a technical reason, or purely cosmetic?

**Comment by tannewt** [comment]
Mostly cosmetic. It will also connect the gnd pin before the others when the target is connected second which is better I think.

**Comment by k0d** [comment]
<img width="523" alt="Screenshot 2020-08-30 at 20 55 40" src="https://user-images.githubusercontent.com/547698/91667226-2d8f0b80-eb03-11ea-82b5-775f25efa322.png">

Is this ok for host? I did the slant going in because otherwise the spider would stick too far into the rest of the PCB and take up unnecessary space.

On the bottom of the PCB, the slant still points into the board...like it was before.

**Comment by tannewt** [comment]
I like it!

**Comment by nitz** [comment]
Same! I'm good with taking up less space that way for sure!

I can't get over how much I dig that little spider!

**Comment by k0d** [comment]
If we want to connect GND first, shouldn't it be longer on the host side also?

**Comment by tannewt** [comment]
Yes but I’m more worried about it being obvious which is host and which is target.

**Comment by k0d** [comment]
Host = Debugger = Spider with his arrow pointing to the ....
....arrow which points to ... Target = MCU

**Comment by k0d** [comment]
<img width="541" alt="Screenshot 2020-08-30 at 22 21 22" src="https://user-images.githubusercontent.com/547698/91668734-266dfa80-eb0f-11ea-9307-2950c20c0ecd.png">
 ok ?

**Comment by tannewt** [comment]
I understand that. I worry that detail is too small and that the of differences would be more immediately obvious.

**Comment by tannewt** [comment]
The host side should be indented while the target would have a longer gnd. I liked the host before.

**Comment by k0d** [comment]
A lot of target boards would use 6 pin I think...at least mine would...SWD and SWO are probably most common...unless it's full jtag like esp32 etc...but still...I'll make the target more different also.

**Comment by tannewt** [comment]
Right. I’m thinking the 10 pin design will apply to the fewer pin designs as well. The spider and the gnd pin are always present.

**Comment by k0d** [comment]
<img width="377" alt="Screenshot 2020-08-30 at 22 29 38" src="https://user-images.githubusercontent.com/547698/91668853-4ce06580-eb10-11ea-8666-bb3f9d10cf72.png">

I had this idea also...and invert the arrow on the target....if you don't like it, I'll go back to the short host GND pad...

**Comment by tannewt** [comment]
Ya I like that! Good idea

**Comment by k0d** [comment]
<img width="390" alt="Screenshot 2020-08-30 at 23 12 12" src="https://user-images.githubusercontent.com/547698/91669583-3fc67500-eb16-11ea-8e1e-bcee3beeb617.png">

It didn't look nice having the arrow point 'in' on the target...what about this?

**Comment by k0d** [comment]
<img width="369" alt="Screenshot 2020-08-30 at 23 17 44" src="https://user-images.githubusercontent.com/547698/91669690-10fcce80-eb17-11ea-88ec-e1bb8037439f.png">

Clearance of the connector...you still can see the 'icons'...

**Comment by k0d** [comment]
<img width="557" alt="Screenshot 2020-08-30 at 23 40 52" src="https://user-images.githubusercontent.com/547698/91670072-48b94580-eb1a-11ea-883a-2656da9e0570.png">

<img width="943" alt="Screenshot 2020-08-30 at 23 38 48" src="https://user-images.githubusercontent.com/547698/91670024-f6782480-eb19-11ea-9b28-612154a00428.png">

<img width="743" alt="Screenshot 2020-08-30 at 23 40 01" src="https://user-images.githubusercontent.com/547698/91670052-232c3c00-eb1a-11ea-989c-e9cba799d5b1.png">

"Final version" ;)

**Comment by tannewt** [comment]
Looks great!

**Comment by nitz** [comment]
Absolutely fantastic. I really appreciate all the work you're putting into this. The footprint looks so dang awesome!

**Comment by tannewt** [comment]
@k0d You should have permissions to push all of this to the repo.

**Comment by k0d** [comment]
Yeah....will tidy things up, and push in the next couple of days.

**Comment by k0d** [comment]
I have boards now, they work well. However the silkscreen and spidey/mcu logos are a bit hard to see. I want to make some small changes, but nothing major.

**Comment by k0d** [comment]
Quite a big change...but it'll be much easier to recognise the footprint.

<img width="568" alt="Screenshot 2020-09-12 at 08 20 14" src="https://user-images.githubusercontent.com/547698/92988975-e0cb0d80-f4d0-11ea-9245-e5a2dd470df7.png">

**Comment by k0d** [comment]
OLD:
<img width="200" alt="Screenshot 2020-09-12 at 08 52 32" src="https://user-images.githubusercontent.com/547698/92989553-63ee6280-f4d5-11ea-9288-32d6f0d7632d.png">
NEW:
<img width="200" alt="Screenshot 2020-09-12 at 08 52 54" src="https://user-images.githubusercontent.com/547698/92989554-651f8f80-f4d5-11ea-89b9-b0ce973fbeb1.png">

**Comment by k0d** [comment]
I like this....and you @nitz @tannewt ?

<img width="1028" alt="Screenshot 2020-09-12 at 09 36 41" src="https://user-images.githubusercontent.com/547698/92990296-85eae380-f4db-11ea-89fc-8bbe0f421b12.png">
<img width="986" alt="Screenshot 2020-09-12 at 09 35 08" src="https://user-images.githubusercontent.com/547698/92990293-82575c80-f4db-11ea-8de3-7e72787f4c6e.png">

**Comment by tannewt** [comment]
I like that the arrow is clearer but why straighten the pads?

**Comment by k0d** [comment]
I had to make the MCU bigger...so the pads had to be straight...but on the back...they're still pointed.

I think this makes it clearer which side is which.

The main issue is that if we have the MCU too close to the pads, we loose the solder mask...and it looks ugly.

**Comment by tannewt** [comment]
Ok! Thanks for iterating on the design.

**Comment by k0d** [comment]
<img width="1243" alt="Screenshot 2020-09-12 at 11 58 13" src="https://user-images.githubusercontent.com/547698/92993114-bf2d4e80-f4ef-11ea-9411-fcd96b7fd090.png">
<img width="1252" alt="Screenshot 2020-09-12 at 11 59 02" src="https://user-images.githubusercontent.com/547698/92993117-c05e7b80-f4ef-11ea-93a5-eadf51ccf06e.png">

Ok, so I think I'm done with my updates. I like the MCU a lot more. It will be way easier to get fab'd, I've also updated Spidey a little so he's more fab'able.

**Comment by nitz** [comment]
Is the center of the IC art just bare FR4? Cause that's super clever!

I kinda liked the way the spider was "holding" the arrow" before, but I will definitely yield that it is certainly clearer.

I'm thrilled with your artistic ability :)

**Comment by k0d** [comment]
Yeah, it's bare FR4. It really helps with the 0.2mm solder mask spacing requirement. I really like how it looks, especially on the green/HASL which is what I have to use a lot of the time. Next order I do will have black/ENIG though.

I also liked it that the spider was spinning an arrow-web, but I think we have to go with clarity in this case. We could of course make the logo have it spinning the arrow...I've not thought much about that yet.
