### ISSUE TITLE
Move 'master' branch to 'main'

### ISSUE THREAD

**Issue by k0d** [nitz/OpenClip#8]

**Comment by nitz** [comment]
I'm not quite sure what you meant by this one

**Comment by k0d** [comment]
@tannewt will know I'm sure.

https://www.bbc.com/news/technology-53050955

**Comment by nitz** [comment]
Yup, great idea. I've pushed a branch named main, but I don't have project settings access so I can't delete master nor set main as default, so @tannewt's got to do that!

**Comment by tannewt** [comment]
Done! Thank you!
